/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as RhRouteImport } from './routes/rh'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MembersRouteImport } from './routes/members'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalPacksRouteImport } from './routes/portal.packs'
import { Route as PortalLogbookRouteImport } from './routes/portal.logbook'
import { Route as PortalAvailabilityRouteImport } from './routes/portal.availability'
import { Route as PortalAccountRouteImport } from './routes/portal.account'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPacksRoute = PortalPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLogbookRoute = PortalLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAvailabilityRoute = PortalAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/administration': typeof AdministrationRoute
  '/assets': typeof AssetsRoute
  '/discovery': typeof DiscoveryRoute
  '/finance': typeof FinanceRoute
  '/flights': typeof FlightsRoute
  '/integrations': typeof IntegrationsRoute
  '/members': typeof MembersRoute
  '/planning': typeof PlanningRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/purchases': typeof PurchasesRoute
  '/reporting': typeof ReportingRoute
  '/rh': typeof RhRoute
  '/sales': typeof SalesRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/availability': typeof PortalAvailabilityRoute
  '/portal/logbook': typeof PortalLogbookRoute
  '/portal/packs': typeof PortalPacksRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/administration': typeof AdministrationRoute
  '/assets': typeof AssetsRoute
  '/discovery': typeof DiscoveryRoute
  '/finance': typeof FinanceRoute
  '/flights': typeof FlightsRoute
  '/integrations': typeof IntegrationsRoute
  '/members': typeof MembersRoute
  '/planning': typeof PlanningRoute
  '/pricing': typeof PricingRoute
  '/purchases': typeof PurchasesRoute
  '/reporting': typeof ReportingRoute
  '/rh': typeof RhRoute
  '/sales': typeof SalesRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/availability': typeof PortalAvailabilityRoute
  '/portal/logbook': typeof PortalLogbookRoute
  '/portal/packs': typeof PortalPacksRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/administration': typeof AdministrationRoute
  '/assets': typeof AssetsRoute
  '/discovery': typeof DiscoveryRoute
  '/finance': typeof FinanceRoute
  '/flights': typeof FlightsRoute
  '/integrations': typeof IntegrationsRoute
  '/members': typeof MembersRoute
  '/planning': typeof PlanningRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/purchases': typeof PurchasesRoute
  '/reporting': typeof ReportingRoute
  '/rh': typeof RhRoute
  '/sales': typeof SalesRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/availability': typeof PortalAvailabilityRoute
  '/portal/logbook': typeof PortalLogbookRoute
  '/portal/packs': typeof PortalPacksRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/administration'
    | '/assets'
    | '/discovery'
    | '/finance'
    | '/flights'
    | '/integrations'
    | '/members'
    | '/planning'
    | '/portal'
    | '/pricing'
    | '/purchases'
    | '/reporting'
    | '/rh'
    | '/sales'
    | '/portal/account'
    | '/portal/availability'
    | '/portal/logbook'
    | '/portal/packs'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/administration'
    | '/assets'
    | '/discovery'
    | '/finance'
    | '/flights'
    | '/integrations'
    | '/members'
    | '/planning'
    | '/pricing'
    | '/purchases'
    | '/reporting'
    | '/rh'
    | '/sales'
    | '/portal/account'
    | '/portal/availability'
    | '/portal/logbook'
    | '/portal/packs'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/administration'
    | '/assets'
    | '/discovery'
    | '/finance'
    | '/flights'
    | '/integrations'
    | '/members'
    | '/planning'
    | '/portal'
    | '/pricing'
    | '/purchases'
    | '/reporting'
    | '/rh'
    | '/sales'
    | '/portal/account'
    | '/portal/availability'
    | '/portal/logbook'
    | '/portal/packs'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AdministrationRoute: typeof AdministrationRoute
  AssetsRoute: typeof AssetsRoute
  DiscoveryRoute: typeof DiscoveryRoute
  FinanceRoute: typeof FinanceRoute
  FlightsRoute: typeof FlightsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MembersRoute: typeof MembersRoute
  PlanningRoute: typeof PlanningRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportingRoute: typeof ReportingRoute
  RhRoute: typeof RhRoute
  SalesRoute: typeof SalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/packs': {
      id: '/portal/packs'
      path: '/packs'
      fullPath: '/portal/packs'
      preLoaderRoute: typeof PortalPacksRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/logbook': {
      id: '/portal/logbook'
      path: '/logbook'
      fullPath: '/portal/logbook'
      preLoaderRoute: typeof PortalLogbookRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/availability': {
      id: '/portal/availability'
      path: '/availability'
      fullPath: '/portal/availability'
      preLoaderRoute: typeof PortalAvailabilityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalAvailabilityRoute: typeof PortalAvailabilityRoute
  PortalLogbookRoute: typeof PortalLogbookRoute
  PortalPacksRoute: typeof PortalPacksRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalAvailabilityRoute: PortalAvailabilityRoute,
  PortalLogbookRoute: PortalLogbookRoute,
  PortalPacksRoute: PortalPacksRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AdministrationRoute: AdministrationRoute,
  AssetsRoute: AssetsRoute,
  DiscoveryRoute: DiscoveryRoute,
  FinanceRoute: FinanceRoute,
  FlightsRoute: FlightsRoute,
  IntegrationsRoute: IntegrationsRoute,
  MembersRoute: MembersRoute,
  PlanningRoute: PlanningRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  PurchasesRoute: PurchasesRoute,
  ReportingRoute: ReportingRoute,
  RhRoute: RhRoute,
  SalesRoute: SalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
